### PR TITLE
Fix BSP reimport issue

### LINKED ISSUE #4641: BSP reimports not always working in Intellij
BSP refresh Image don't always work in Intellj.
After checking out and adding printlns everywhere in the [Intellij Scala plugin](https://github.com/JetBrains/intellij-scala) and mill code, I understand that's because mill is stopping the BSP server prematurely while Intellij still thinks the BSP connection is alive.

# Reproduce

* Open a mill project in Intellij
* Try to reimport BSP Image
* You will see the BSP server getting shutdown in the logs Image:
  ```
  Executing /Users/jgoyeau/IdeaProjects/playback/mill -i mill.bsp.BSP/install
  Entered workspaceReload
  Reloading workspace...
  Unsetting evaluator on session end
  Updating Evaluator: None
  workspaceReload took 1 msec
  workspaceReload result: ()
  Reload finished, result: mill.bsp.BspServerResult$ReloadWorkspace$@5cf8676a
  BSP/startSession: Finished BSP session, result: mill.bsp.BspServerResult$ReloadWorkspace$@5cf8676a
  Entered workspaceBuildTargets
  `mill.bsp.BSP/startSession` returned with Some(mill.bsp.BspServerResult$ReloadWorkspace$@5cf8676a)
  Exiting BSP runner loop. Stopping BSP server. Last result: Some(mill.bsp.BspServerResult$ReloadWorkspace$@5cf8676a)
  Stopping server via handle...
  Exception in thread "Thread-0" java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:54)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:50)
	at mill.bsp.worker.BspWorkerImpl.startBspServer$$anonfun$2(BspWorkerImpl.scala:88)
	at java.base/java.lang.Thread.run(Thread.java:833)
  Updating Evaluator: Some(List(mill.eval.Evaluator@3663d0ba, mill.eval.Evaluator@575cabf0))
  BSP/startSession: Starting BSP session
  ```
* The import will pretend to continue until it fails after a ~10min timeout Image

# Workaround

Stop the BSP connection Image at the bottom before reimporting Image.

Thanks

### PR DESCRIPTION
**Pull request by joan38**
Fixes #4641, tho I'm not 100% sure if this is the right thing to do.

### CODE REVIEW

File: runner/src/mill/runner/MillMain.scala [hunk 1]
```diff
@@ -313,13 +313,13 @@ object MillMain {
                       }
 
                       loopRes = (isSuccess, evalStateOpt)
-                    } // while repeatForBsp
```
Comment (joan38) [inline runner/src/mill/runner/MillMain.scala:316]: That bracket is not closing the while loop

**Comment by lihaoyi** [comment]
Can you fill out the PR description what problem you noticed that this PR solves?

**Comment by joan38** [comment]
Done @lihaoyi

**Comment by lihaoyi** [comment]
Looks good I think, thanks! will merge once CI is done
