### PR TITLE
Show gpg output in server/client in publish (fix #387)

### LINKED ISSUE #387: The publish task should display an error message when the user does not have a gpg secret key
### Current output

```
$ mill hamster[2.11.11].jvm.publish --gpgPassphrase passphrase --release false --sonatypeCreds "user:password"
```
```
[125/125] hamster[2.11.11].jvm.publish
1 targets failed
hamster[2.11.11].jvm.publish ammonite.ops.InteractiveShelloutException
    ammonite.ops.Shellout$.executeInteractive(Shellout.scala:56)
    ammonite.ops.Shellout$.$anonfun$$percent$1(Shellout.scala:14)
    ammonite.ops.Shellout$.$anonfun$$percent$1$adapted(Shellout.scala:14)
    ammonite.ops.Command.applyDynamic(Shellout.scala:118)
    mill.scalalib.publish.SonatypePublisher.poorMansSign(SonatypePublisher.scala:144)
    mill.scalalib.publish.SonatypePublisher.$anonfun$publishAll$4(SonatypePublisher.scala:34)
    scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    scala.collection.Iterator.foreach(Iterator.scala:944)
    scala.collection.Iterator.foreach$(Iterator.scala:944)
```

**NOTE:** When using the interactive mode with the `-i` flag the error message is display:

```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

### Expected output

```
$ mill hamster[2.11.11].jvm.publish --gpgPassphrase passphrase --release false --sonatypeCreds "user:password"
```
```
[125/125] hamster[2.11.11].jvm.publish
1 targets failed
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
hamster[2.11.11].jvm.publish ammonite.ops.InteractiveShelloutException
    ammonite.ops.Shellout$.executeInteractive(Shellout.scala:56)
    ammonite.ops.Shellout$.$anonfun$$percent$1(Shellout.scala:14)
    ammonite.ops.Shellout$.$anonfun$$percent$1$adapted(Shellout.scala:14)
    ammonite.ops.Command.applyDynamic(Shellout.scala:118)
    mill.scalalib.publish.SonatypePublisher.poorMansSign(SonatypePublisher.scala:144)
    mill.scalalib.publish.SonatypePublisher.$anonfun$publishAll$4(SonatypePublisher.scala:34)
    scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    scala.collection.Iterator.foreach(Iterator.scala:944)
    scala.collection.Iterator.foreach$(Iterator.scala:944)
```

We could go one step further and capture the error message from the `gpg`command line to help the user.

```
[125/125] hamster[2.11.11].jvm.publish
1 targets failed
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
You need to set up a GPG key to sign artifacts. Generate a new key, using the following command: "gpg --gen-key".
```

I think the user will also need to publish the key:
```
$ gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --send-keys <key-id>
```

### PR DESCRIPTION
**Pull request by lolgab**
Avoid using `os.Inherit` which is known to break the output in server/client mode.

Fixes #387
Checked manually and the errors now appear with and without `-i`.

### CODE REVIEW

File: scalalib/src/publish/SonatypePublisher.scala [hunk 1]
```diff
@@ -174,8 +175,7 @@ class SonatypePublisher(
     val fileName = file.toString
     val command = "gpg" +: args :+ fileName
 
-    os.proc(command.map(v => v: Shellable))
-      .call(stdin = os.Inherit, stdout = os.Inherit, stderr = os.Inherit)
+    Jvm.runSubprocess(command, Map.empty[String, String], workingDir = null)
```
Comment (lefou) [inline scalalib/src/publish/SonatypePublisher.scala:178]: Why are you setting `workingDir` explicitly to `null`? (The current implementation is handling it as `os.pwd`.) Besides being ugly and non-idiomatic, it may not always be the right location. I think using [`T.workspace`](https://com-lihaoyi.github.io/mill/mill/Task_Context_API.html#_mill_api_ctx_workspace) is the better option here.

**Review by lefou — COMMENTED** [review]
Great catch. This change makes sense. One thing though...

File: scalalib/src/publish/SonatypePublisher.scala (hunk 1 above)
Comment (lolgab) [reply scalalib/src/publish/SonatypePublisher.scala:178]: Are you sure the current implementation is handling as `os.pwd`?
My understanding is that we are calling `os.proc()` which by default uses `null` as `cwd`
https://github.com/com-lihaoyi/os-lib/blob/main/os/src-jvm/ProcessOps.scala#L53

To better match the current behavior I need to pass `sys.env` as the env instead of an empty `Map`.

Comment (lefou) [reply scalalib/src/publish/SonatypePublisher.scala]: Yeah, I think so.

https://github.com/com-lihaoyi/os-lib/blob/6b31f388799743b1410110e474a47ac372aa4be4/os/src-jvm/ProcessOps.scala#L120

But it's an undocumented (I think) implementation detail, so I'd prefer to make it explicit.

Comment (lefou) [reply scalalib/src/publish/SonatypePublisher.scala]: Also, the current env should come via `T.env`, as sys.env might be stale in server-mode, and this whole PR is about improving server-mode, right?

Comment (lolgab) [reply scalalib/src/publish/SonatypePublisher.scala]: Yes, you are right!
When `cwd` is `null` it fallbacks to `os.pwd`:
```scala
@ os.proc("pwd").call(cwd = null).out.text
res1: String = """/Users/lorenzo
"""

@ os.proc("pwd").call(cwd = os.pwd).out.text
res2: String = """/Users/lorenzo
"""
```

Comment (lolgab) [reply scalalib/src/publish/SonatypePublisher.scala]: Now, `SonatypePublisher` doesn't know `Ctx` and can't access `T.workspace` or `T.env`. Should I deprecate the APIs and define new ones that receive `implicit ctx: Ctx`? It's a bit of work though

Comment (lolgab) [reply scalalib/src/publish/SonatypePublisher.scala]: Since the class was already receiving a `Logger` explicitly via `T.log`, I added another two parameters, `workspace` and `env` and I'm passing `T.workspace` and `T.env`. In the deprecated constructor, I'm using `sys.env` and `os.pwd` instead.

Comment (lefou) [reply scalalib/src/publish/SonatypePublisher.scala]: The only issue I see with this approach is, that there is a chance the created instance is used when the context is no longer valid. Should be no issue for `Ctx.workspace` or `Ctx.log` (although misleading) , but `Ctx.dest` of `Ctx.env` could be already invalid. 

As a compromise, we can keep it this way for now, but schedule a rework of the Publisher API to the next major release. I already have a tracker ticket for that:

* https://github.com/com-lihaoyi/mill/discussions/1826

Comment (lolgab) [reply scalalib/src/publish/SonatypePublisher.scala]: I understand the issue.
Currently, we create a fresh instance of `SonatypePublisher` every time so it's not an issue internally. But we can change the API when we are in the next breaking window (0.11.x)

**Review by lefou — APPROVED** [review]
Looks good to me. Thank you!
