### PR TITLE
Android: Generate test_config.properties

### LINKED ISSUE #6620: Android: Support Robolectric unit tests
While the latest version of Mill makes [Jetcaster.wear](https://github.com/vaslabs-ltd/compose-samples-with-mill/pull/21) runnable, we've discovered that Roboelectric unit tests need additional work.

Basically, it seems that a similar flow with instrumented tests (build wise) is needed, as these tests run in a JVM instead of an emulator - that to me implies that what we have in the instrumented tests classpath, needs to be in the unit tests classpath as well. So far, we just took care of only jvm relevant artifacts/assets.

Running the jetcaster unit test gives:

```
Test com.example.jetcaster.NavigationTest.launchAndNavigate failed: java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.robolectric.default/com.example.jetcaster.MainActivity } -- see https://github.com/robolectric/robolectric/pull/4736 for details, took 0.915 sec
801]     at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:101)
801]     at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:36)
801]     at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:41)
801]     at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:367)
801]     at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:203)
801]     at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0(ActivityScenarioRule.java:77)
801]     at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:112)
```

## What does that mean?

It seems to me the namespace of the app Roboelectric is looking is different (`org.robolectric.default`) from what we give in the manifest (user package) and so the activity cannot be found.

There's relevant information in the PR logged by the error, but we need to investigate which information is relevant to mill and probably some reverse engineering will be needed.

My suspicion is that the plugin:

`alias libs.plugins.roborazzi` (io.github.takahirom.roborazzi) takes care of the manipulation of the manifest or other resources.

In addition, the gradle option:

```
    testOptions {
        unitTests {
            includeAndroidResources true
        }
    }
```

feels relevant  ~~but we already include the resources in the unit tests (but maybe not the flat files?)~~

EDIT latter introduced in https://github.com/com-lihaoyi/mill/pull/6638

### PR DESCRIPTION
**Pull request by souvlakias**
Closes #6620 

This adds to the support for the `isIncludeAndroidResources` that was introduced in https://github.com/com-lihaoyi/mill/pull/6638, by generating the `com/android/tools/test_config.properties` file as described [here (agp docs)](https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/api/dsl/UnitTestOptions#getIsIncludeAndroidResources()).

This also makes roboelectric unit tests work (Ref: [jetcaster.wear](https://github.com/vaslabs-ltd/compose-samples-with-mill/blob/main/Jetcaster/package.mill#L442) and the [koin example](https://github.com/com-lihaoyi/mill/pull/6833))

### CODE REVIEW

File: libs/androidlib/src/mill/androidlib/AndroidModule.scala [hunk 1]
```diff
@@ -930,8 +944,36 @@ trait AndroidModule extends JavaModule { outer =>
...
 
+    /**
+     * Generates a Java properties file required when [[androidIncludeAndroidResources]] is true,
+     * containing necessary information for the Android resource processing in unit tests.
+     *
+     * Properties and expected name on the classpath are defined at
+     * [[https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/api/dsl/UnitTestOptions#getIsIncludeAndroidResources()]]
+     */
+    def androidGeneratedTestConfigSources: T[Seq[PathRef]] = Task {
+      val properties: Map[String, String] = Map(
```
Comment (vaslabs) [inline libs/androidlib/src/mill/androidlib/AndroidModule.scala]: we can make this into a separate task so we have more flexibility debugging/fixing issues in the future and allow for easier workarounds

**Comment by vaslabs** [comment]
does it also fix the tests in https://github.com/com-lihaoyi/mill/pull/6833 ? (maybe need to add include android resources as true there too)

ah yeah it does, you mentioned it, sorry

I thought it might have issues with [mocked default values](https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/api/dsl/UnitTestOptions#getIsReturnDefaultValues()) but maybe it's not hitting it

**Comment by vaslabs** [comment]
amazing work, nice one @souvlakias
