### PR TITLE
Fixes: #3550 ; Add hello-world Android Java Example using Mill

### LINKED ISSUE #3550: Add hello-world Android Java & Kotlin examples using Mill (2000USD bounty)
---

**From the maintainer Li Haoyi**: I'm putting a 2000USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

We have a bunch of examples for generic library dev and backend server dev (spring-boot, micronaut), but we don't have any android examples.

Something like https://hereket.com/posts/android_from_command_line/ or https://github.com/authmane512/android-project-template could be good references.

As this is a large bounty, I'm breaking it down into four pieces:

1. [x] 500USD Android Java Support:

* A folder in `example/javalib/android/1-hello-world` that contains a build that contains Java code for building a trivial hello-world android app APK, that can then be loaded into a physical phone or android emulator. 
* Just the simplest plain-old-Java android app is fine: no need fancier features or C++ code or whatever. 
* Manual testing of the final APK is fine, but the process to build it should be exercised in the example. 
* The app should have two modules containing Java code, one depending on another, to demonstrate how splitting of a app codebase into modules works
* Android-specific config should be extracted into a `trait AndroidJavaModule` in `mill.javalib`, and only app-specific config should be in the `example/javalib/android/1-hello-world` example
* Both the library code and the example code should be rigorously documented w.r.t. how it is used and how it fits into the larger Android ecosystem

2. [x] 500USD Testing Android Java Example

* A more sophisticated version of the example in (1) above, demonstrating usage of:

    * Unit testing and Integration testing your android app
    * Third-party library dependencies (https://developer.android.com/build/dependencies)

4. [x] 500USD Android Kotlin Support: 

* Same as (1) above, except for Kotlin: `example/kotlinlib/android/1-hello-world`, plain-old-Kotlin code, manual testing, two modules, with a `trait AndroidKotlinModule` in `mill.kotlinlib`

5. [x] 500USD Jetpack Compose Example

* A hello-world example demonstating usage of the Jetpack Compose framework for Android with Kotlin

### PR DESCRIPTION
**Pull request by himanshumahajan138**
## Description
This PR fixes #3550 by adding a "hello-world" Android Java example using Mill.

### Changes:
- **Created `1-hello-world` folder** inside `example/javalib/android`
  - This folder contains a `src` folder for sources and a `build.mill` file.
- **Created two modules:**
  - `AndroidSdkModule.scala`: This module handles the SDK setup.
  - `AndroidAppModule.scala`: This module extends both `AndroidSdkModule` and `JavaModule` to ensure proper functionality. 
- In `build.mill`, extended the `App` module for building the Android application.
- `android_examples.adoc` created and referred in navbar.adoc, finally tested.
- Documentation done for android modules and build.mill and finally tested
- Code is fully documented with references taken from `example/{javalib,kotlinlib,scalalib}` and `scalalib/{Modules...}`.
- All the Documentation is checked locally (worlking as expected for `scaladoc{AndroidAppModule, AndroidScalaModule}`)
- Documentation and explanation of the code are embedded as comments within the code.
- Included a screenshot of the application to demonstrate its functionality.

### Type of Change
- [x] New feature (non-breaking change which adds functionality)

## Related Issues
issue #3550

## Testing
Tested by building the Android app using Mill, ensuring that both the `AndroidSdkModule` and `AndroidAppModule` work together as expected. Successfully generated the APK and verified the "Hello World" functionality.

## Checklist
- [x] Created 1-hello-world folder with build.mill and sources
- [x] Created two modules AndroidAppModule.scala and AndroidSdkModule.scala
- [x] Created documentation file android_examples.adoc, above two modules also done.
- [x] Code builds and passes all tests.
- [x] Documentation Tested with local doc's creation
- [x] I have added comments in the code where necessary, updated the documentation accordingly.
- [x] Any dependent changes have been merged and published.

## Additional Notes
Feel free to review the code and let me know if any further improvements are needed.

### Screenshots
hello-world-android

### CODE REVIEW

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+   *
+   * - Installs essential components such as platform-tools, build-tools and platforms.
+   *
+   * @see [[SdkUrl]]
+   * @see [[toolsDirectory]]
+   * @see [[sdkDirectory]]
+   * @see [[BuildToolsVersion]]
+   * @see [[PlatformVersion]]
+   */
+  def installAndroidSdk: T[Unit] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidSdkModule.scala:146]: This should return `T[PathRef]`. There should not be a `sdkDirectory`, `androidSdk` should download and unpack the SDK zip into its own `T.dest`

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+   * @return A `PathRef` representing the path to the AAPT tool.
+   *
+   * @see [[buildToolsPath]]
+   */
+  def aaptPath: T[PathRef] = T { PathRef(buildToolsPath().path / "aapt") }
+
+  /**
+   * Path to Zipalign, used to optimize APKs.
+   *
+   * @return A `PathRef` representing the path to the zipalign tool.
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidSdkModule.scala:112]: We should not repeat the same docs twice in the scaladoc. If there is only one line of docs to say, then just say that one line

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+        createApk().path.toString, // Use the unsigned APK from createApk
+        alignedApk.toString // Specify output aligned APK file
+      )
+    )
+
+    PathRef(alignedApk) // Return the path to the aligned APK.
+  }
+
+  /**
+   * Step 6: Sign the APK using a keystore.
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:199]: We should not have `Step n` prefixes here, because they are not stable and are not useful to someone understanding what a particular task does

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+   * Path where the Project related Files will live.
+   *
+   * @return A `PathRef` representing project directory.
+   */
+  def projectRoot: T[os.Path] = T {
+    os.Path(millSourcePath.toString.replace(
+      "App",
+      ""
+    )) // Get the parent directory of millSourcePath
+  }
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: This should not exist

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 5]
```diff
@@ -0,0 +1,276 @@
...
+ * 4. Package DEX files and resources into an APK.
+ *
+ * 5. Optimize the APK using zipalign.
+ *
+ * 6. Sign the APK for distribution.
+ *
+ * For detailed information, refer to Mill's Documentation [[https://com-lihaoyi.github.io/mill]],
+ * and the Android Dcoumentation [[https://developer.android.com/studio]].
+ */
+trait AndroidAppModule extends AndroidSdkModule with JavaModule {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:31]: This should not extend `AndroidSdkModule`, and should instead take it as an abstract `def` that gets overridden to point at a separately instantiated `AndroidSdkModule` in the example, to ensure we can share the same SDK between different apps if necessary

File: example/javalib/android/1-hello-world/build.mill [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+// This Example demonstrates a simple "Hello World" 
+// Android application built using the https://www.lihaoyi.com/mill[Mill build tool].
+
+//// SNIPPET:BUILD
+package build
+
+import mill._
+import mill.javalib.android.AndroidAppModule
+
+object App extends AndroidAppModule {
```
Comment (lihaoyi) [inline example/javalib/android/1-hello-world/build.mill:16]: Modules should be lowercase

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 7]
```diff
@@ -0,0 +1,276 @@
...
+   *
+   * - Ensures the Android SDK is installed.
+   *
+   * - Compiles all `.java` files in `src/main/java` to `.class` files stored in `obj/` directory.
+   *
+   * @return A `PathRef` to the directory containing the compiled `.class` files.
+   *
+   * @see [[createJar]]
+   */
+  def compileJava: T[PathRef] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:65]: We should not have our own custom `compileJava`, we should just use `compile`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 8]
```diff
@@ -0,0 +1,276 @@
...
+   * This method:
+   *
+   * - Converts the compiled `.class` files into a JAR file using the `d8` tool.
+   *
+   * @return A `PathRef` to the generated JAR file.
+   *
+   * @see [[compileJava]]
+   * @see [[createDex]]
+   */
+  def createJar: T[PathRef] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:96]: This does not create a `jar`, this creates a `dex`, and should be named appropriately

Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:96]: We should override the existing `jar` target rather than creating our own.

What is the difference between the jars created by `d8` and the jars created by `jar`? That should be explained in the scaladoc

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 9]
```diff
@@ -0,0 +1,276 @@
...
+   * Step 2: Package `.class` files into a JAR file.
+   *
+   * This method:
+   *
+   * - Converts the compiled `.class` files into a JAR file using the `d8` tool.
+   *
+   * @return A `PathRef` to the generated JAR file.
+   *
+   * @see [[compileJava]]
+   * @see [[createDex]]
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:94]: We don't need `see` annotations, users can jump to def on the various references in the method body already

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 10]
```diff
@@ -0,0 +1,276 @@
...
+   *
+   * This method:
+   *
+   * - Uses the `d8` tool to convert the JAR file into DEX format, required for Android apps.
+   *
+   * @return A `PathRef` to the generated DEX file.
+   *
+   * @see [[createJar]]
+   */
+  def createDex: T[PathRef] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:124]: The naming conventions for this kind of trait-specific task is to prefix it with the name of the trait: `androidDex`, `androidApk`, `androidAppName`, `androidApp`, `androidKeystore` etc. to mitigate the risk of name collisions

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala [hunk 11]
```diff
@@ -0,0 +1,175 @@
...
+ * and the Android Dcoumentation [[https://developer.android.com/studio]].
+ */
+trait AndroidSdkModule extends Module {
+
+  /**
+   * URL to download the Android SDK command-line tools.
+   *
+   * @return A string representing the URL for the SDK tools.
+   */
+  def SdkUrl: T[String] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidSdkModule.scala:25]: camelCase not PascalCase

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 12]
```diff
@@ -0,0 +1,276 @@
...
+ * and the Android Dcoumentation [[https://developer.android.com/studio]].
+ */
+trait AndroidAppModule extends AndroidSdkModule with JavaModule {
+
+  /**
+   * Path where the Project related Files will live.
+   *
+   * @return A `PathRef` representing project directory.
+   */
+  def projectRoot: T[os.Path] = T {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:38]: `T{...}` should be `Task{...}` throughout

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 13]
```diff
@@ -0,0 +1,276 @@
...
+          "RSA", // Key algorithm
+          "-keysize",
+          "2048", // Key size
+          "-storepass",
+          "android", // Keystore password
+          "-keypass",
+          "android" // Key password
+        )
+      )
+    }
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:272]: Every task shelling out to a third-party binary should contain a link to the docs for the third party binary where you got the command from

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 7 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:65]: @lihaoyi Actually i was trying to implement this thing from past 3 days and experimented alot but the problem is that we have custom android sdk and jar path and even after providing path to them in the compile module doesn't solves the error of `Android.os` not found , `Android.app` not found and so on amd these errors come on the MainActivity.java file.

Finally after alot of experiments i thought there are only two parameters to provide why not we use traditional method of compiling(as i did)

Please help me in this if you know how to solve this Android.__ not found error (i have read alot of docs still didn't got it )

Here is what i was doing:
```
def sources: T[Seq[PathRef]] = Task.Sources{
    super.sources() ++ Seq(PathRef(projectRoot / "java"))
  }

  def unmanagedClasspath: T[Agg[PathRef]] = Task {
    Agg(androidJarPath())
  }

  def javacOptions = Seq(
    "-bootclasspath",
    androidJarPath().path.toString,
    "-classpath",
    androidJarPath().path.toString,
    "-sourcepath",
    (projectRoot / "java").toString,
  )


  /**
   * Packages the compiled `.class` files into a JAR file using the `d8` tool.
   *
   * The `d8` tool converts the `.class` files into Android-compatible format,
   * and creates a `.jar` file without desugaring.
   *
   * @return A `PathRef` pointing to the generated `.jar` file.
   */
  def createJar: T[PathRef] = T {
    installAndroidSdk()
    val jarFile: os.Path = T.dest / "my_classes.jar"
    os.call(
      Seq(
        d8Path().path.toString, // D8 tool path
        "--output",
        jarFile.toString, // Output .jar file
        "--no-desugaring" // Disable desugaring
      ) ++ os.walk(compile().classes.path).filter(_.ext == "class").map(
        _.toString
      ) // Input .class files
    )

    PathRef(jarFile)
  }
```

Comment (lihaoyi) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:65]: @himanshumahajan138 I can't help you solve all these problems, the point of the ticket is that you are helping me solve these problems. I'm not familiar with the android toolchain.

As I mentioned before, if you are unable to solve them that's fine, and I won't fault you for not doing so. But if you want to try to close the bounty, you'll need to figure it out.

File: example/javalib/android/1-hello-world/build.mill (hunk 6 above)
Comment (himanshumahajan138) [reply example/javalib/android/1-hello-world/build.mill:16]: done

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala (hunk 2 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidSdkModule.scala:112]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 3 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:199]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 10 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:124]: done

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala (hunk 11 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidSdkModule.scala:25]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 12 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:38]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 9 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:94]: done

File: scalalib/src/mill/javalib/android/AndroidSdkModule.scala (hunk 1 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidSdkModule.scala:146]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 5 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:31]: i did this in following way:

in AndroidAppModule.scala
```
trait AndroidAppModule extends JavaModule {

  /**
   * Abstract method to provide the AndroidSdkModule instance.
   * This allows sharing the same SDK between different apps.
   */
  def androidSdkModule: AndroidSdkModule

}
```

and in the build.mill 

```
import mill.javalib.android.{AndroidAppModule,AndroidSdkModule}

object app extends AndroidAppModule {

  // Create an instance of AndroidSdkModule
  object sdkModule extends AndroidSdkModule

  // Override androidSdkModule to return the sdkModule instance
  override def androidSdkModule: AndroidSdkModule = sdkModule
  }
  ```
  
  Its functioning as expected i will add some docs on how its implemented

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 4 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: following is what i did, this will ensure general path for every build and is working as expected (PathRefs returned by upstream tasks)

why i used ".." ? 
- because millSourcePath provides path appended with current object like in our case it will give `path/to/project/app` here `app` is our object we created in `build.mill`
- so to ensure we are in project folder directory we used ".." to get one directory back to our project folder 

and then finally we created it as a task to return PathRef and the output from this will get as a upstream output to the functions which are using it 

@lihaoyi Is this Correct Approach to handle?

```
  /**
   * Path where the Project related Files will live.
   *
   * @return A `PathRef` representing project directory.
   */
  def projectRoot: T[PathRef] = T {
    PathRef(millSourcePath / "..")
  }
  ```

Comment (lihaoyi) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: Why do you need `projectRoot`?

Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: because sir we need to get src folder files

Comment (lihaoyi) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: How does `JavaModule` get the `src/` folder files?

Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: this is the way done in javamodule

```

 /**
   * The folders where the source files for this module live
   */
  def sources: T[Seq[PathRef]] = Task.Sources { millSourcePath / "src" }

  /**
   * The folders where the resource files for this module live.
   * If you need resources to be seen by the compiler, use [[compileResources]].
   */
  def resources: T[Seq[PathRef]] = Task.Sources { millSourcePath / "resources" }

  /**
   * The folders where the compile time resource files for this module live.
   * If your resources files do not necessarily need to be seen by the compiler,
   * you should use [[resources]] instead.
   */
  def compileResources: T[Seq[PathRef]] = Task.Sources { millSourcePath / "compile-resources" }

  /**
   * Folders containing source files that are generated rather than
   * hand-written; these files can be generated in this target itself,
   * or can refer to files generated from other targets
   */
  def generatedSources: T[Seq[PathRef]] = Task { Seq.empty[PathRef] }

  /**
   * The folders containing all source files fed into the compiler
   */
  def allSources: T[Seq[PathRef]] = Task { sources() ++ generatedSources() }

  /**
   * All individual source files fed into the Java compiler
   */
  def allSourceFiles: T[Seq[PathRef]] = Task {
    Lib.findSourceFiles(allSources(), Seq("java")).map(PathRef(_
    ))
  }
  
  ```

Comment (lihaoyi) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:43]: yes

**Comment by himanshumahajan138** [comment]
@lihaoyi Sir please don't get irritated by my doubts(i am newbie) please clear my last doubt...

basically when i reviewed `Json` files(allSources.json, allSourceFiles.json .....so on) in the `out` folder:
```
allSources.json

{
    "value": [
        "ref:v0:c984eca8:/home/himanshu138/opensource/himanshu/mill/out/example/javalib/android/1-hello-world/local/testCached.dest/sandbox/run-1/app/src"
    ],
    "valueHash": -2002708993,
    "inputsHash": 1715811750
}

allSourceFiles.json

{
    "value": [],
    "valueHash": 1467096776,
    "inputsHash": 435515105
}
```
so after this i came to know that even `JavaModule` is unable to pick up my `src` files because it is also get `path` added with `app` becoz of which i am getting error of `no source files` and then i checked all previous `examples/javalib/` and found this :
```
object `package` extends RootModule with JavaModule {...}
```
and when i tried this same thing then i got shocked this time it got the files and sources, see:
```
what i tired
object `package` extends RootModule with AndroidAppModule {...}

allSources.json
{
    "value": [
        "ref:v0:49c3a842:/home/himanshu138/opensource/himanshu/mill/out/example/javalib/android/1-hello-world/local/testCached.dest/sandbox/run-1/src"
    ],
    "valueHash": -1645131398,
    "inputsHash": 1044320490
}

allSourceFiles.json
{
    "value": [
        "ref:v0:60186141:/home/himanshu138/opensource/himanshu/mill/out/example/javalib/android/1-hello-world/local/testCached.dest/sandbox/run-1/src/main/java/com/helloworld/app/MainActivity.java"
    ],
    "valueHash": -249522556,
    "inputsHash": -470604943
}

```

Final Verdict: we also need to use `package` and make androidApp as a RootModule object

please share your thoughts and suggestions...

**Comment by lihaoyi** [comment]
Yes the filesystem hierarchy has to match the module hierarchy

**Comment by himanshumahajan138** [comment]
> Yes the filesystem hierarchy has to match the module hierarchy

Thanks Alot Sir finally now i got answers to all of my doubts...

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 5 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:31]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 7 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:65]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 13 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:272]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 8 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:96]: Point of View and Explanation:

- **D8 Compiler**: 
  - Converts Java bytecode into DEX (Dalvik Executable) files specifically for Android.
  - Optimizes code for Android devices, resulting in better performance.

- **Benefits of Using D8**:
  - **Size Reduction**: JARs created by D8 are likely smaller.
  - **Optimizations**: D8 can apply optimizations like desugaring, which allows newer Java language features to be used effectively.

- **Standard JAR Command**:
  - Simply packages class files without Android-specific optimizations.
  - Does not include the performance enhancements available in D8.

- **Conclusion**: 
  - Using D8 for creating JARs leads to smaller, faster applications tailored for the Android ecosystem.
  
 I will include mini-version of this information in scaladoc

**Comment by himanshumahajan138** [comment]
@lihaoyi Thankyou Sir for the detailed feedback! 

I’ve addressed all the requested changes and resolved the comments. Please let me know if anything else needs attention.

Please pardon me if I missed anything or made a mistake. Looking forward to your final review and any further suggestions!

**Comment by lihaoyi** [comment]
Thanks @himanshumahajan138 , I think it looks pretty good overall, let me try running some end-to-end tests on an android emulate on my laptop and then we can close this out

**Comment by himanshumahajan138** [comment]
Thanks @lihaoyi Sir It's You who gave me another chance to show up my skills and contribute to Mill.

I hope all the tests pass successfully🤞

File: example/javalib/android/1-hello-world/build.mill [hunk 14]
```diff
@@ -0,0 +1,81 @@
...
+  // Create and configure an Android SDK module to manage Android SDK paths and tools.
+  object sdkModule extends AndroidSdkModule
+
+  // Override the `androidSdkModule` to link to our custom `sdkModule`, which provides 
+  // Android SDK toolchain (e.g., `aapt`, `d8`, `zipalign`, `apksigner`).
+  override def androidSdkModule: AndroidSdkModule = sdkModule
+
+  // Define the Android application name. Defaults to "HelloWorld", but can be customized 
+  // by overriding this value in the project.
+  def androidAppName: T[String] = T { "HelloWorld" }
```
Comment (lihaoyi) [inline example/javalib/android/1-hello-world/build.mill:26]: Let's get rid of this and just hard-code the name of the android application name as `app.apk`. If anyone cares to change it they can `override def androidApk` and `os.copy` the old path to a new one, so we don't need to provide name customization hooks built in

File: example/javalib/android/1-hello-world/build.mill [hunk 15]
```diff
@@ -0,0 +1,81 @@
...
+import mill.javalib.android.{AndroidAppModule, AndroidSdkModule}
+
+object `package` extends RootModule with AndroidAppModule {
+
+  // Create and configure an Android SDK module to manage Android SDK paths and tools.
+  object sdkModule extends AndroidSdkModule
+
+  // Override the `androidSdkModule` to link to our custom `sdkModule`, which provides 
+  // Android SDK toolchain (e.g., `aapt`, `d8`, `zipalign`, `apksigner`).
+  override def androidSdkModule: AndroidSdkModule = sdkModule
```
Comment (lihaoyi) [inline example/javalib/android/1-hello-world/build.mill:22]: I think we can consolidate these two into `object androidSdkModule extends AndroidSdkModule`, which will automatically override the abstract `def androidSdkModule`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 16]
```diff
@@ -0,0 +1,333 @@
...
+   *
+   * If no keystore is available, a new one is generated using the `keytool` utility.
+   *
+   * For more details on the apksigner tool, refer to:
+   * [[https://developer.android.com/tools/apksigner apksigner Documentation]]
+   *
+   * @return A `PathRef` pointing to the signed APK.
+   */
+  def androidApp: T[PathRef] = Task {
+    val signedApk: os.Path = millSourcePath / s"${androidAppName().toString}.apk"
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:268]: We should not be writing to `millSourcePath`. This should live in `T.dest` like any other generated file; if the user isn't sure where it is, they can always use `mill show`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 17]
```diff
@@ -0,0 +1,333 @@
...
+  /**
+   * Packages the DEX files and Android resources into an unsigned APK using the `aapt` tool.
+   *
+   * The `aapt` tool takes the DEX files (compiled code) and resources (such as layouts and assets),
+   * and packages them into an APK (Android Package) file. This APK file is unsigned and requires
+   * further processing to be distributed.
+   *
+   * @return A `PathRef` pointing to the unsigned APK file.
+   */
+  def androidApk: T[PathRef] = Task {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:204]: Let's call this `androidUnsignedApk`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 18]
```diff
@@ -0,0 +1,333 @@
...
+   * This is required for better performance on Android devices. This step is done after the APK
+   * is created but before it is signed.
+   *
+   * For more details on the zipalign tool, refer to:
+   * [[https://developer.android.com/tools/zipalign zipalign Documentation]]
+   *
+   * @return A `PathRef` pointing to the aligned APK file.
+   */
+  def androidAlignApk: T[PathRef] = Task {
+    val alignedApk: os.Path = T.dest / s"${androidAppName().toString}.aligned.apk"
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:237]: Let's call this `androidAlignedUnsignedApk`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 19]
```diff
@@ -0,0 +1,333 @@
...
+   * along with a keystore file to sign the APK.
+   *
+   * If no keystore is available, a new one is generated using the `keytool` utility.
+   *
+   * For more details on the apksigner tool, refer to:
+   * [[https://developer.android.com/tools/apksigner apksigner Documentation]]
+   *
+   * @return A `PathRef` pointing to the signed APK.
+   */
+  def androidApp: T[PathRef] = Task {
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:267]: Let's call this `androidApk`

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala [hunk 20]
```diff
@@ -0,0 +1,333 @@
...
+   * Conclusion: Using D8 for creating JARs ensures smaller, faster applications optimized
+   * for the Android ecosystem.
+   *
+   * For more details on the d8 tool, refer to:
+   * [[https://developer.android.com/tools/d8 d8 Documentation]]
+   *
+   * @return A `PathRef` pointing to the generated JAR file.
+   */
+  def androidJar: T[PathRef] = Task {
+    val jarFile: os.Path = T.dest / "my_classes.jar"
```
Comment (lihaoyi) [inline scalalib/src/mill/javalib/android/AndroidAppModule.scala:154]: let's call this `app.jar`

**Comment by lihaoyi** [comment]
Tested locally on my android emulator, works great on my macbook. A few final comments and we can merge it.

**Comment by himanshumahajan138** [comment]
That's great Sir I will do the required changes and push the final code asap

Thanks Alot @lihaoyi  Sir

File: example/javalib/android/1-hello-world/build.mill (hunk 14 above)
Comment (himanshumahajan138) [reply example/javalib/android/1-hello-world/build.mill:26]: sir i think we can remove this from the build.mill file but what about the one present in the AndroidAppModule.scala please see:
```

  /**
   * Defines the name of the Android application.
   *
   * The name is used as part of the APK file name (e.g., `HelloWorld.apk`), and also
   * helps distinguish different builds. It defaults to "HelloWorld", but can be
   * overridden for custom app names.
   *
   * @return The name of the Android application as a String.
   */
  def androidAppName: T[String] = Task { "HelloWorld" }
  
  ```
  i think we should keep and change its value to `app` so that if user wants to change the name of the application they can override this task and change name accordingly 

Final Thoughts?

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 16 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:268]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 17 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:204]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 18 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:237]: done

File: scalalib/src/mill/javalib/android/AndroidAppModule.scala (hunk 19 above)
Comment (himanshumahajan138) [reply scalalib/src/mill/javalib/android/AndroidAppModule.scala:267]: done

File: example/javalib/android/1-hello-world/build.mill (hunk 15 above)
Comment (himanshumahajan138) [reply example/javalib/android/1-hello-world/build.mill:22]: done

**Comment by himanshumahajan138** [comment]
@lihaoyi Sir Finally It's done, Thank you so much sir for your help and support

**Comment by lihaoyi** [comment]
Looks good, merging it and we can tweak it more in main. @himanshumahajan138 can email me your international bank transfer details and I can send you the bounty

**Comment by himanshumahajan138** [comment]
@lihaoyi Sir I have sent the details to your email mentioned in your GitHub account.

Please Confirm the details...
