### PR TITLE
fix zinc binary dependencies

### LINKED ISSUE #1901: Incorrect `zinc` modified binary dependencies
Recently I report incremental compiling not working for me in gitter. After some investigation I found the following zinc log shows that the jdk internal class are marked modified binary dependenices while recompiling.  Seems jdk jars are not in classpath.

```
[debug] Modified binary dependencies: HashSet(/modules/java.base/java/time/ZoneId.class, /modules/java.base/java/time/DayOfWeek.class, /modules/java.base/java/time/Duration.class, /modules/java.base/java/time/Instant.class, /modules/java.base/java/io/Serializable.class, /modules/java.base/java/lang/Class.class, /modules/java.base/java/nio/charset/Charset.class, /modules/java.base/java/security/MessageDigest.class, /modules/java.base/java/time/LocalTime.class, /modules/java.base/java/lang/Throwable.class, /modules/java.base/java/time/temporal/TemporalAccessor.class, /modules/java.base/java/lang/CharSequence.class, /modules/java.base/java/nio/charset/StandardCharsets.class, /modules/java.base/java/time/ZonedDateTime.class, /modules/java.base/java/time/chrono/ChronoLocalDate.class, /modules/java.base/java/time/chrono/ChronoLocalDateTime.class, /modules/java.base/java/time/chrono/ChronoZonedDateTime.class, /modules/java.base/java/lang/RuntimeException.class, /modules/java.base/java/time/OffsetDateTime.class, /modules/java.base/java/time/LocalDateTime.class, /modules/java.base/java/lang/String.class, /modules/java.base/java/lang/Math.class, /modules/java.base/java/lang/Object.class, /modules/java.base/java/time/format/DateTimeFormatter.class, /modules/java.base/java/time/ZoneOffset.class, /modules/java.base/java/lang/Exception.class, /modules/java.base/java/time/temporal/ChronoUnit.class, /modules/java.base/java/time/LocalDate.class, /modules/java.base/java/time/temporal/Temporal.class)
```

```
[debug] Invalidating '/modules/java.base/java/time/Instant.class' because could not find class java.time.Instant on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/Throwable.class' because could not find class java.lang.Throwable on the classpath.
[debug] Invalidating '/modules/java.base/java/time/ZoneOffset.class' because could not find class java.time.ZoneOffset on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/RuntimeException.class' because could not find class java.lang.RuntimeException on the classpath.
[debug] Invalidating '/modules/java.base/java/nio/charset/Charset.class' because could not find class java.nio.charset.Charset on the classpath.
[debug] Invalidating '/modules/java.base/java/time/ZoneId.class' because could not find class java.time.ZoneId on the classpath.
[debug] Invalidating '/modules/java.base/java/io/Serializable.class' because could not find class java.io.Serializable on the classpath.
[debug] Invalidating '/modules/java.base/java/time/OffsetDateTime.class' because could not find class java.time.OffsetDateTime on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/Exception.class' because could not find class java.lang.Exception on the classpath.
[debug] Invalidating '/modules/java.base/java/time/temporal/TemporalAccessor.class' because could not find class java.time.temporal.TemporalAccessor on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/CharSequence.class' because could not find class java.lang.CharSequence on the classpath.
[debug] Invalidating '/modules/java.base/java/time/LocalDateTime.class' because could not find class java.time.LocalDateTime on the classpath.
[debug] Invalidating '/modules/java.base/java/time/DayOfWeek.class' because could not find class java.time.DayOfWeek on the classpath.
[debug] Invalidating '/modules/java.base/java/time/temporal/ChronoUnit.class' because could not find class java.time.temporal.ChronoUnit on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/String.class' because could not find class java.lang.String on the classpath.
[debug] Invalidating '/modules/java.base/java/time/Duration.class' because could not find class java.time.Duration on the classpath.
[debug] Invalidating '/modules/java.base/java/time/LocalDate.class' because could not find class java.time.LocalDate on the classpath.
[debug] Invalidating '/modules/java.base/java/nio/charset/StandardCharsets.class' because could not find class java.nio.charset.StandardCharsets on the classpath.
[debug] Invalidating '/modules/java.base/java/time/chrono/ChronoLocalDateTime.class' because could not find class java.time.chrono.ChronoLocalDateTime on the classpath.
[debug] Invalidating '/modules/java.base/java/security/MessageDigest.class' because could not find class java.security.MessageDigest on the classpath.
[debug] Invalidating '/modules/java.base/java/time/temporal/Temporal.class' because could not find class java.time.temporal.Temporal on the classpath.
[debug] Invalidating '/modules/java.base/java/time/LocalTime.class' because could not find class java.time.LocalTime on the classpath.
[debug] Invalidating '/modules/java.base/java/time/ZonedDateTime.class' because could not find class java.time.ZonedDateTime on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/Math.class' because could not find class java.lang.Math on the classpath.
[debug] Invalidating '/modules/java.base/java/time/chrono/ChronoLocalDate.class' because could not find class java.time.chrono.ChronoLocalDate on the classpath.
[debug] Invalidating '/modules/java.base/java/time/chrono/ChronoZonedDateTime.class' because could not find class java.time.chrono.ChronoZonedDateTime on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/Object.class' because could not find class java.lang.Object on the classpath.
[debug] Invalidating '/modules/java.base/java/time/format/DateTimeFormatter.class' because could not find class java.time.format.DateTimeFormatter on the classpath.
[debug] Invalidating '/modules/java.base/java/lang/Class.class' because could not find class java.lang.Class on the classpath.
```

Note, this log can be turned on by changing logger level in  `ZincWorkerImpl` to `Debug`
 ```scala
LogExchange.bindLoggerAppenders(loggerId, (consoleAppender -> sbt.util.Level.Info) :: Nil)
```
And most my source files referring to `java.time` related classes.
Also, this not apply to `sbt`,  `sbt` did incremental compiling without any issue.

### PR DESCRIPTION
**Pull request by jilen**
Fix #1901 
Sbt use a `MappedFileConverter`, it will converter `jdk` internal classes like `/module/java.base/java.lang.String` associated with a dummpy `rt.jar`.
https://github.com/sbt/zinc/blob/57d03412abe3810be5762a8c8e8c55cbf622ed03/internal/zinc-core/src/main/scala/sbt/internal/inc/MappedVirtualFile.scala#L56
```scala
def toVirtualFile(path: Path): VirtualFile = {
    rootPaths2.find { case (_, rootPath) => path.startsWith(rootPath) } match {
      case Some((key, rootPath)) =>
        MappedVirtualFile(s"$${$key}/${rootPath.relativize(path)}".replace('\\', '/'), rootPaths)
      case _ =>
        def isCtSym =
          path.getFileSystem
            .provider()
            .getScheme == "jar" && path.getFileSystem.toString.endsWith("ct.sym")
        def isJrt = path.getFileSystem.provider().getScheme == "jrt"
        if (isJrt || path.getFileName.toString == "rt.jar" || isCtSym)
          DummyVirtualFile("rt.jar", path)
        else if (allowMachinePath) MappedVirtualFile(s"$path".replace('\\', '/'), rootPaths)
        else sys.error(s"$path cannot be mapped using the root paths $rootPaths")
    }
  }
```

And later the `Incremental`  will exclude such binary dependencies.
https://github.com/sbt/zinc/blob/57d03412abe3810be5762a8c8e8c55cbf622ed03/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L783
```scala

        // dependency is some other binary on the classpath.
        // exclude dependency tracking with rt.jar, for example java.lang.String -> rt.jar.
        if (!vf.id.endsWith("rt.jar")) {
          externalLibraryDependency(
            vf,
            onBinaryName,
            sourceFile,
            context
          )
        }
```

### CODE REVIEW

**Comment by lefou** [comment]
About the test failures. I just created 

* #1905 

which fixes an ordering issue in a test, which just popped up for some days. Once it is merged, we can rebase/merge your PR to get CI green.

**Comment by lefou** [comment]
I also created 

* PR #1907 

which _should_ succeed after we apply this fix.

File: scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala [hunk 1]
```diff
@@ -13,6 +13,9 @@ case class MockedLookup(am: VirtualFile => Optional[CompileAnalysis])
   override def analysis(classpathEntry: VirtualFile): Optional[CompileAnalysis] =
     am(classpathEntry)
 
-  override def definesClass(classpathEntry: VirtualFile): DefinesClass =
-    Locate.definesClass(classpathEntry)
+  override def definesClass(classpathEntry: VirtualFile): DefinesClass = {
+    if (classpathEntry.name.toString != "rt.jar")
```
Comment (lefou) [inline scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala:17]: This looks a bit unsafe to me.

First, it only matches on the file name, which could break when there are other jars with the same name in the classpath. 

Second, I don't quite understand why this works at all? Newer JDKs (>8) don't provide a `rt.jar` so in Mill we create one dynamically and place it under `~/.mill/ammonite/rt-${jdk-version}.jar`. So, we should never match this correctly, unless there is some other mapping in action. Do you have some explanation for this?

**Review by lefou — COMMENTED** [review]
Can you please add some details to this PR description. Esp. a motivation for the solution. Also, where does the hard-coded `rt.jar` comes from?

**Comment by lefou** [comment]
Oh, I forgot, this PR indeed seems to fix the issue. #1907 runs successfully.

File: scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala (hunk 1 above)
Comment (jilen) [reply scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala:17]: Not pretty sure, but this is what `sbt` have done.
https://github.com/sbt/sbt/blob/1.7.x/main/src/main/scala/sbt/internal/VirtualFileValueCache.scala#L29
```scala
apply(converter) { x: VirtualFile =>
      if (x.name.toString != "rt.jar") Locate.definesClass(x)
      else (_: String) => false
    }
```

Comment (jilen) [reply scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala:17]: Not if don't have this line, an exception will throw.

Comment (lefou) [reply scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala:17]: Thanks for these insight. If `classpathEntry.name` is the full name, this should be rather collision free.

**Comment by lefou** [comment]
Thank you!
