### PR TITLE
Changed out path for overridden targets for consistency

### LINKED ISSUE #820: AssertionError when using predefScript.sc
Installed mill with homebrew

```
> mill --version
Mill Build Tool version 0.6.1
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_BE, platform encoding: UTF-8
OS name: "Mac OS X", version: 10.15.3, arch: x86_64
```
Followed docs here
http://www.lihaoyi.com/mill/page/configuring-mill.html#global-configuration

And when I start mill I see this:
```
> mill api:compile
Compiling /Users/myuser/.mill/ammonite/predefScript.sc
java.lang.AssertionError: assertion failed
  scala.Predef$.assert(Predef.scala:208)
  mill.define.Segment$Label.<init>(Ctx.scala:14)
  mill.define.Segment$Label$.apply(Ctx.scala:13)
  mill.define.Segment$Label$.apply(Ctx.scala:13)
  scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
  scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
  scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:39)
  scala.collection.TraversableLike.map(TraversableLike.scala:237)
  scala.collection.TraversableLike.map$(TraversableLike.scala:230)
  scala.collection.AbstractTraversable.map(Traversable.scala:108)
  mill.define.Segments$.labels(Ctx.scala:57)
  ammonite.predef.predefScript$.<init>(predefScript.sc:54)
  ammonite.predef.predefScript$.<clinit>(predefScript.sc)
```

Assertion errors are not very user friendly, this could give some more information on what is failing and why

https://github.com/lihaoyi/mill/blob/85aa6bdb1bd1d08fb2739a4fd75dd76b0ab6652c/main/core/src/define/Ctx.scala#L14

### PR DESCRIPTION
**Pull request by lefou**
To be more consistent with the changes from PR
https://github.com/com-lihaoyi/mill/pull/1588
which re-layouted the log, meta, and dest path for targets.
This change touches the path of overriden target results.
It replaces the `../target/overriden/..` part with
`../target.overriden/..`.

There is a catch though, to make this work I had to remove one
`require` assertion, which guarded the presence of dots (`.`) in
labels. TBH, I previously stubled upon this require
and also added the FIXME comment to it, as it is unclear why it
even exists. Probably, because labels with dots can't be properly
parsed when given on cli. More details and hisory can be found in
issue https://github.com/com-lihaoyi/mill/issues/820.

Fix #820.

Review by @lihaoyi.

### CODE REVIEW

**Review by lihaoyi — APPROVED** [review]

**Comment by lihaoyi** [comment]
It would take some refactoring to make the path/segment handling "clean", but I'm fine with removing the assert for now

**Comment by lihaoyi** [comment]
The fundamental issue with that assert is that `Segment` currently (with that assert) models things which can be parsed from the CLI, whereas the `.override` things cannot be parsed from the CLI. Thus using `Segment` to model the `foo.override/` paths is not correct.

One slightly-less-hacky thing we could do is to add a third case to `Segment`, e.g. `Segment.Override` or something, to explicitly model this. Then we can ensure that the parser only returns `Segment.Label` or `Segment.Cross`, but other places we can synthesize `Segment.Override`s as well. That would also be a good direction to go in if we in future decided to allow people to build the overridden targets directly from the CLI, which AFAIK is currently not allowed.

There are probably other things we could do, but this was the solution I thought of off the top of my head.

File: main/core/src/mill/eval/Evaluator.scala [hunk 1]
```diff
@@ -670,12 +670,16 @@ object Evaluator {
...
-          if (!overriden(t)) Nil
-          else
-            Seq(Segment.Label("overriden")) ++ t.ctx.enclosing.split("\\.|#| ").map(Segment.Label)
+        val segments0 = t.ctx.segments
+        val (segments, additional) =
+          if (!overriden(t)) (segments0, Nil)
+          else {
+            val Segment.Label(tName) = segments0.value.last
+            (
+              Segments(segments0.value.reverse.tail.reverse: _*),
```
Comment (lihaoyi) [inline main/core/src/mill/eval/Evaluator.scala:679]: `.reverse.tail.reverse` is just `.init`

File: main/core/src/mill/eval/Evaluator.scala [hunk 2]
```diff
@@ -670,12 +670,16 @@ object Evaluator {
...
+              Seq(Segment.Label(tName + ".overriden")) ++ t.ctx.enclosing.split("\\.|#| ").map(Segment.Label)
```
Comment (lihaoyi) [inline main/core/src/mill/eval/Evaluator.scala:680]: Shall we rename this from `.overriden` to `.override`? or `.overridden` to at least spell it correctly :P

Comment (lefou) [reply main/core/src/mill/eval/Evaluator.scala:680]: I renamed this one at least 3 times in the last two years, but then reverted to avoid nitpicking. Also, after looking into a dictionary, "overriden" is actually not incorrect. But now, as you see it the same, I'd glad to rename it. I think "overridden" is more correct than "override" as the folder is holding the state of "overridden" targets.

File: main/core/src/mill/eval/Evaluator.scala (hunk 1 above)
Comment (lefou) [reply main/core/src/mill/eval/Evaluator.scala:679]: Wow, I'm using Scala for more than 10 years; today I learned something new.

**Comment by lihaoyi** [comment]
On second thoughts, the `.overriden` data can only apply once to an entire `Segments`, and thus should apply to `Segments` as a whole and not be a replacement for any individual `Segment`

**Comment by lefou** [comment]
@lihaoyi Nice thing it, this PR actually fixed #820.

**Comment by lefou** [comment]
I'd like to keep the mapping to `Segment` as-is for now. Parsing is at some degree unrelated, as the removed `require` was just an after-the-fact guard and there is still a unique mapping of parsables to segments. The only issue is, that it's not bidirectional, but we don't generate cli arguments from segments, do we? (If we do, e.g. when completing, we could filter them out.) We could come up with some quoting or escaping, if someone really needs that feature, which is rather unlikely.

**Comment by lihaoyi** [comment]
@lefou we actually do generate a string from the `Segments` data structure in a few places via `Segments#render`, e.g. to populate the `mill-profile.json`.

I don't think we actually need it to be parseable - in the end it's just for debugging purposes - so I'm happy to merge this PR as is and figure out a way to clean things up later
