### PR TITLE
Fix #370 Use ExtClassLoader instead of null as parent

### LINKED ISSUE #370: `zipfs` library classes missing from runtime classpath when testing
(mill 0.2.3)

## Project Structure

`build.sc`:

```scala
import mill._, mill.scalalib._
object foo extends ScalaModule {
  def scalaVersion = "2.12.4"
  object test extends Tests {
    def ivyDeps = Agg(ivy"com.lihaoyi::utest:0.6.0")
    def testFrameworks = Seq("utest.runner.Framework")
  }
}
```

`foo/test/src/Main.scala`:

```scala
import com.sun.nio.zipfs._
object Main {
  def main(args: Array[String]): Unit = {
    println(classOf[ZipFileSystemProvider])
  }
}
```

`foo/test/src/Test.scala`:

```scala
import com.sun.nio.zipfs._
import utest._
object Test extends TestSuite {
  println(classOf[ZipFileSystemProvider])
  val tests = Tests {}
}
```

## `mill foo.test.run` works

Prints:

```
class com.sun.nio.zipfs.ZipFileSystemProvider
```

## `mill foo.test` throws `NoClassDefFoundError`

```
-------------------------------- Running Tests --------------------------------
X Test 0ms
  java.lang.NoClassDefFoundError: com/sun/nio/zipfs/ZipFileSystemProvider
    Test$.<init>(Test.scala:4)
    Test$.<clinit>(Test.scala:-1)
    sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:-2)
    sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
    sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
    java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
    java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
    java.lang.reflect.Field.get(Field.java:393)
    utest.runner.BaseRunner.$anonfun$runSuite$1(BaseRunner.scala:97)
  java.lang.ClassNotFoundException: com.sun.nio.zipfs.ZipFileSystemProvider
    java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    mill.util.ClassLoader$$anon$2.super$findClass(ClassLoader.scala:33)
    mill.util.ClassLoader$$anon$2.$anonfun$findClass$1(ClassLoader.scala:33)
    scala.Option.getOrElse(Option.scala:121)
    mill.util.ClassLoader$$anon$2.findClass(ClassLoader.scala:33)
    java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    Test$.<init>(Test.scala:4)
    Test$.<clinit>(Test.scala:-1)
    sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:-2)
    sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
    sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
    java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
    java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
    java.lang.reflect.Field.get(Field.java:393)
    utest.runner.BaseRunner.$anonfun$runSuite$1(BaseRunner.scala:97)
1 targets failed
foo.test.test Test Test.
```

## Notes
- I've tried to ask mill for relevant `runClasspath`s and `compileClasspath`s, but haven't seen leads for debugging this.
- It happens for all classes under `com.sun.nio.zipfs._`, which come from the `zipfs.jar` JDK module.
- The same thing happens if I use e.g. scalatest runner instead of utest.

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

File: scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+import utest._
+
+object ClassLoaderTests extends TestSuite {
+  try {
+    getClass().getClassLoader().loadClass("com.sun.nio.zipfs.ZipFileSystemProvider")
+  } catch {
+    case _: ClassNotFoundException if !System.getProperty("java.specification.version").startsWith("1.") =>
+      // Don't fail on Java 9+
+  }
+  val tests = Tests {}
```
Comment (lefou) [inline scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala:12]: a bit nitpicking, but wouldn't it be nicer to read, when we move the part that can fail into a test?

File: main/api/src/mill/api/ClassLoader.scala [hunk 2]
```diff
@@ -69,6 +69,19 @@ object ClassLoader {
...
+      // We get the application classloader parent which happens to be of
+      // type sun.misc.Launcher$ExtClassLoader
+      // We can't call the method directly since it doesn't exist in Java 9
+      // So we load it via reflection.
+      val launcherClass = getClass.getClassLoader().loadClass("sun.misc.Launcher")
+      val getLauncherMethod = launcherClass.getMethod("getLauncher")
+      val launcher = getLauncherMethod.invoke(null)
+      val getClassLoaderMethod = launcher.getClass().getMethod("getClassLoader")
+      val appClassLoader = getClassLoaderMethod.invoke(launcher).asInstanceOf[ClassLoader]
+      appClassLoader.getParent()
```
Comment (lefou) [inline main/api/src/mill/api/ClassLoader.scala:84]: Why do we load this code via reflection, when we are only supposed to run it on Java 8? It this more the kind of compile-time work-around?

Comment (lolgab) [reply main/api/src/mill/api/ClassLoader.scala:84]: The code doesn't compile in Java 9+. I used reflection to allow compilation of Mill in Java 9+ since the `sun.misc` package doesn't exist in Java 9+.

File: scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala (hunk 1 above)
Comment (lolgab) [reply scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala]: Refactored the test. 👍

File: main/api/src/mill/api/ClassLoader.scala (hunk 2 above)
Comment (lefou) [reply main/api/src/mill/api/ClassLoader.scala:84]: Thanks for clarifying. I think the comment is kind of abḿbigous. Maybe, you can add, that reflection solved an issue at compilation-time?

File: scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala (hunk 1 above)
Comment (lefou) [reply scalalib/test/resources/classloader-test/test/src/ClassLoaderTests.scala]: Nice

File: main/api/src/mill/api/ClassLoader.scala (hunk 2 above)
Comment (lolgab) [reply main/api/src/mill/api/ClassLoader.scala]: Rephrased the commend a bit.

**Review by lefou — COMMENTED** [review]
Looks good to me. Now, we need to find out. why this isn't working on Windows. 🤔

**Comment by lolgab** [comment]
> Looks good to me. Now, we need to find out. why this isn't working on Windows. 🤔

It was not happy with `*` in the test name. It seems fine now.

**Review by lefou — APPROVED** [review]
